name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - name: Run fmt check script
        run: deno fmt --check
      - name: Run lint script
        run: deno lint --unstable
